name: .NET

on:
  push:
    branches: [ 8-publish-nuget ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ctftools.tests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" 
    - name: Pack the project and find .nupkg files
      run: |
        dotnet pack
        find . -type f -name "*.nupkg"
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2

